Algoritmo "Atv13"

Var

letra : caractere

Inicio

escreva ("Digite o seu caractere: ")
leia (letra)
se letra = caractere entao
   se (letra = "a", "e", "i", "o", "u") entao
   escreval ("Seu caractere é uma vogal")
   senao
   escreval ("Seu caractere é uma consoante")
fimse
senao se letra = int entao
escreval ("Seu caractere é um número")
senao
escreval ("Seu caractere é um símbolo")
fimse

Fimalgoritmo