Algoritmo "Atv4"

Var

n : inteiro

Inicio

escreval ("Digite um número")
leia (n)
se (n % 2 = 0) entao
escreval ("Seu número é divisível por 2")
senao
escreval ("Seu número não é divisível por 2")
fimse

se (n % 5 = 0) entao
escreval ("Seu número é divisível por 5")
senao
escreval ("Seu número não é divisível por 5")
fimse

se (n % 10 = 0) entao
escreval ("Seu número é divisível por 10")
senao
escreval ("Seu número não é divisível por 10")
fimse

Fimalgoritmo